/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TechnicianAndResearch;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TechnicianRequest;
import Business.WorkQueue.WorkRequest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komal
 */
public class TechnicianWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TechnicianJPanel
     */
    private JPanel container;
    private UserAccount account;
    private Organization org;
    private Enterprise enterprise;
    private EcoSystem system;
    public TechnicianWorkAreaJPanel(JPanel container,UserAccount account, Organization org, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.container = container;
        this.account = account;
        this.org = org;
        this.enterprise= enterprise;
        this.system = system;
        populateReqTable();  
        techEstimateDate.setDate(new Date());
    }
    
    public void populateReqTable() {
        DefaultTableModel model = (DefaultTableModel) tblNotifyTechnicin.getModel();
        model.setRowCount(0);

        for (WorkRequest work : system.getWorkQueue().getWorkRequestList()) {
            if (work instanceof TechnicianRequest) {
                Object[] row = new Object[9];
                row[0] = work;
                row[1] = work.getMachine();
                row[2] = work.getMachine().getCode();
                row[3] = ((TechnicianRequest) work).getServiceType();
                row[4] = ((TechnicianRequest) work).getDescription();
                row[5] = work.getStatus();
                row[6] = work.getSender();
                row[7] = work.getReceiver();
                row[8] = ((TechnicianRequest) work).getServiceDateInString();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotifyTechnicin = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblProblemDesc = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnViewDesc = new javax.swing.JButton();
        btnAssigntoMe = new javax.swing.JButton();
        techEstimateDate = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Technician work area");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 137, 16);

        tblNotifyTechnicin.setBackground(new java.awt.Color(204, 255, 204));
        tblNotifyTechnicin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNotifyTechnicin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblNotifyTechnicin.setForeground(new java.awt.Color(102, 0, 102));
        tblNotifyTechnicin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RequestId", "Machine", "Code", "Type of service", "Description", "Status", "Sender", "Technician", "Possible date of Assistance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNotifyTechnicin);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 45, 950, 230);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Problem Description:");
        add(jLabel7);
        jLabel7.setBounds(50, 330, 134, 16);

        lblProblemDesc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblProblemDesc.setForeground(new java.awt.Color(0, 102, 0));
        lblProblemDesc.setText("Problem mention from the hospital/ngo/uhc/lab");
        add(lblProblemDesc);
        lblProblemDesc.setBounds(200, 330, 271, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Date of providing service");
        add(jLabel8);
        jLabel8.setBounds(50, 380, 163, 16);

        btnViewDesc.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDesc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewDesc.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDesc.setText("View Description");
        btnViewDesc.setMaximumSize(new java.awt.Dimension(200, 200));
        btnViewDesc.setMinimumSize(new java.awt.Dimension(200, 200));
        btnViewDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDescActionPerformed(evt);
            }
        });
        add(btnViewDesc);
        btnViewDesc.setBounds(580, 320, 180, 40);

        btnAssigntoMe.setBackground(new java.awt.Color(0, 153, 153));
        btnAssigntoMe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssigntoMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssigntoMe.setText("Assign to me");
        btnAssigntoMe.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigntoMeActionPerformed(evt);
            }
        });
        add(btnAssigntoMe);
        btnAssigntoMe.setBounds(240, 450, 180, 40);
        add(techEstimateDate);
        techEstimateDate.setBounds(250, 380, 116, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDescActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblNotifyTechnicin.getSelectedRow();
        if (selectedrow >= 0) {
            TechnicianRequest request = (TechnicianRequest) tblNotifyTechnicin.getValueAt(selectedrow, 0);
            lblProblemDesc.setText(request.getDescription());
            Date oDate = techEstimateDate.getDate();
            DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
            String szDate = oDateFormat.format(oDate);
            request.setServiceDateInString(szDate);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Request!!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewDescActionPerformed

    private void btnAssigntoMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigntoMeActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblNotifyTechnicin.getSelectedRow();
        if (selectedrow >= 0) {

            TechnicianRequest request = (TechnicianRequest) tblNotifyTechnicin.getValueAt(selectedrow, 0);
            lblProblemDesc.setText(request.getDescription());

            if (request.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                Date oDate = techEstimateDate.getDate();
                Date now = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
                if ((sdf.format(oDate).equals(sdf.format(now))) || (sdf.format(oDate).compareTo(sdf.format(now))) > 0) {
                    DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
                    String szDate = oDateFormat.format(oDate);
                    request.setReceiver(this.account);
                    request.setStatus("Completed");
                    request.setDayOfDelivery(szDate);
                    techEstimateDate.setDate(oDate);
                    populateReqTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Date of Delivery", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Request!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAssigntoMeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntoMe;
    private javax.swing.JButton btnViewDesc;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblProblemDesc;
    private javax.swing.JTable tblNotifyTechnicin;
    private org.jdesktop.swingx.JXDatePicker techEstimateDate;
    // End of variables declaration//GEN-END:variables
}
