/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Email.Email;
import Business.Network.Network;
import Business.WorkQueue.MachineRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komal
 */
public class ManageLoanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageLoanJPanel
     */
    private JPanel container;
    private EcoSystem system;
    private ArrayList<Network> network;

    public ManageLoanJPanel(JPanel container, ArrayList<Network> network, EcoSystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        this.network = network;
        populateTable();
    }

    public void populateTable() {

        Date d = new Date();
        DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
        String szDate = oDateFormat.format(d);

        DefaultTableModel dtm = (DefaultTableModel) tblLoanLog.getModel();
        dtm.setRowCount(0);

        for (WorkRequest req : system.getWorkQueue().getWorkRequestList()) {
            if (req instanceof MachineRequest) {

                DecimalFormat df = new DecimalFormat("#.00");

                Object row[] = new Object[11];
                row[0] = req.getMachine().getName();
                row[1] = req.getMachine().getCode();
                row[2] = ((MachineRequest) req);
                row[3] = df.format(((MachineRequest) req).getTotalPrice());
                row[4] = df.format(((MachineRequest) req).getInstallmentPrice());
                int noOfInstallment = ((MachineRequest) req).getNoOfInstallmentsRemaining();
                row[5] = noOfInstallment;
                row[6] = ((MachineRequest) req).getPaymentDateInString();
                if (noOfInstallment > 0) {
                    row[7] = df.format(((MachineRequest) req).getRemainingAmount());
                    row[8] = ((MachineRequest) req).getNextDateOfInstallmentInString();
                } else {
                    row[7] = 0;
                    row[8] = "-";
                }

                if (szDate.equals(((MachineRequest) req).getNextDateOfInstallmentInString())) {
                    row[9] = "Email sent";

                } else {
                    row[9] = " ";
                }
                row[10] = req.getSender();
            dtm.addRow(row);
           

                if (szDate.equals(((MachineRequest) req).getNextDateOfInstallmentInString())) {
                    Email mail = new Email();
                    //panchal.k@husky.neu.edu
                    mail.sendEmail(req.getSender().getEmployee().getEmailId(), "Installment Due Remainder", "Hello, " + req.getSender().getEmployee().getName()
                            + " This is the kind remainder for your next installment payment.", "kranti1995@gmail.com", "kranti1995", "Jaygurudev151", "Bill_ks.pdf");
                }
            }
        }
    }

    /**
* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLoanLog = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Loan Status");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 78, 16);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 450, 55, 39);

        tblLoanLog.setBackground(new java.awt.Color(204, 255, 204));
        tblLoanLog.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblLoanLog.setForeground(new java.awt.Color(102, 0, 102));
        tblLoanLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Machine", "Code", "Quantity", "Price", "Installment", "No of Installments", "Payment Date", "Remaining Amount", "Next Due Date", "Email Status", "User"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblLoanLog);

        add(jScrollPane3);
        jScrollPane3.setBounds(30, 40, 1130, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);


    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JTable tblLoanLog;
    // End of variables declaration//GEN-END:variables
}
