/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.WorkQueue.MachineRequest;
import Business.WorkQueue.WorkRequest;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komal
 */
public class RequestsForMachinefromClientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form REquestsForMachineJPanel
     */
    private JPanel container;
    private EcoSystem system;
    private ArrayList<Network> network;
    
    public RequestsForMachinefromClientJPanel(JPanel container,ArrayList<Network> network,EcoSystem system) {
        initComponents();
        this.container = container;
        this.system =system;
        this.network=network;
        machineDetails.hide();
        emailBox.hide();
        btnGenerateBill.setEnabled(false);
        populateTable();
                
    }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblReqfromClients.getModel();
        dtm.setRowCount(0);

        for (WorkRequest r : system.getWorkQueue().getWorkRequestList()) {
            if (r instanceof MachineRequest) {
                Object[] row = new Object[10];
                row[0] = r;
                row[1] = r.getMachine();
                row[2] = r.getMachine().getCode();
                row[3] = ((MachineRequest) r).getRequestQuantity();
                double totalAmount = ((MachineRequest) r).getTotalPrice();
                DecimalFormat df = new DecimalFormat("#.00");
                row[4] = df.format(totalAmount);
                row[5] = r.getSender().getRole();
                row[6] = r.getSender();
                row[7] = r.getStatus();
                row[8] = r.getReceiver() == null ? null : r.getReceiver().getEmployee().getName();
                row[9] = r.getDayOfDelivery();

                dtm.addRow(row);
            }
            txtMailAdd.setText(r.getSender().getEmployee().getEmailId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomername1 = new javax.swing.JLabel();
        emailBox = new javax.swing.JInternalFrame();
        txtMailAdd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMailSubject = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMailMessage = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtAttached = new javax.swing.JTextField();
        btnAttached = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        machineDetails = new javax.swing.JInternalFrame();
        lblMachineName = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPrise = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSender = new javax.swing.JLabel();
        lblReceiver = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDateOfDelivery = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSendMail = new javax.swing.JButton();
        btnGenerateBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReqfromClients = new javax.swing.JTable();
        btnSendSupplier = new javax.swing.JButton();
        btnViewDet = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Machine Requests from Clients");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 199, 16);

        emailBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailBox.setClosable(true);
        emailBox.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        emailBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emailBox.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        emailBox.setFocusCycleRoot(false);
        emailBox.setName("emailBox"); // NOI18N
        emailBox.setOpaque(true);
        emailBox.setVisible(true);
        emailBox.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                emailBoxInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        emailBox.getContentPane().setLayout(null);

        txtMailAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMailAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailBox.getContentPane().add(txtMailAdd);
        txtMailAdd.setBounds(70, 10, 250, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("To:");
        emailBox.getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 10, 19, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("Subject:");
        emailBox.getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 60, 51, 15);

        txtMailSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMailSubject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailBox.getContentPane().add(txtMailSubject);
        txtMailSubject.setBounds(70, 50, 250, 30);

        txtMailMessage.setColumns(20);
        txtMailMessage.setRows(5);
        txtMailMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtMailMessage);

        emailBox.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 90, 250, 120);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 51));
        jLabel18.setText("Message:");
        emailBox.getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 100, 56, 15);

        txtAttached.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAttached.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailBox.getContentPane().add(txtAttached);
        txtAttached.setBounds(70, 220, 250, 30);

        btnAttached.setBackground(new java.awt.Color(0, 153, 153));
        btnAttached.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAttached.setForeground(new java.awt.Color(255, 255, 255));
        btnAttached.setText("Attache File");
        btnAttached.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAttached.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAttached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachedActionPerformed(evt);
            }
        });
        emailBox.getContentPane().add(btnAttached);
        btnAttached.setBounds(210, 260, 109, 25);

        btnSend.setBackground(new java.awt.Color(0, 153, 153));
        btnSend.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send ");
        btnSend.setMaximumSize(new java.awt.Dimension(200, 200));
        btnSend.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        emailBox.getContentPane().add(btnSend);
        btnSend.setBounds(130, 300, 100, 25);

        add(emailBox);
        emailBox.setBounds(930, 220, 350, 380);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        machineDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        machineDetails.setClosable(true);
        machineDetails.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        machineDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        machineDetails.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        machineDetails.setFocusCycleRoot(false);
        machineDetails.setName("machineDetails"); // NOI18N
        machineDetails.setOpaque(true);
        machineDetails.setVisible(true);
        machineDetails.getContentPane().setLayout(null);

        lblMachineName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMachineName.setForeground(new java.awt.Color(0, 102, 0));
        lblMachineName.setText("*Machine");
        machineDetails.getContentPane().add(lblMachineName);
        lblMachineName.setBounds(120, 30, 61, 16);

        lblCode.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCode.setForeground(new java.awt.Color(0, 102, 0));
        lblCode.setText("*MCode");
        machineDetails.getContentPane().add(lblCode);
        lblCode.setBounds(120, 60, 51, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Code");
        machineDetails.getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 60, 32, 16);

        lblPrise.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPrise.setForeground(new java.awt.Color(0, 102, 0));
        lblPrise.setText("*amount");
        machineDetails.getContentPane().add(lblPrise);
        lblPrise.setBounds(120, 120, 120, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Price");
        machineDetails.getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 120, 32, 16);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("Sender");
        machineDetails.getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 30, 46, 16);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 0));
        jLabel15.setText("Details");
        machineDetails.getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 10, 44, 16);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("Quantity");
        machineDetails.getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 90, 56, 16);

        lblQty.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblQty.setForeground(new java.awt.Color(0, 102, 0));
        lblQty.setText("*qty");
        machineDetails.getContentPane().add(lblQty);
        lblQty.setBounds(120, 90, 30, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Machine");
        machineDetails.getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 30, 53, 16);

        lblSender.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSender.setForeground(new java.awt.Color(0, 102, 0));
        lblSender.setText("*sender");
        machineDetails.getContentPane().add(lblSender);
        lblSender.setBounds(420, 30, 80, 16);

        lblReceiver.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblReceiver.setForeground(new java.awt.Color(0, 102, 0));
        lblReceiver.setText("*receiver");
        machineDetails.getContentPane().add(lblReceiver);
        lblReceiver.setBounds(420, 90, 90, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Receiver");
        machineDetails.getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 90, 57, 16);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 102, 0));
        lblStatus.setText("*status");
        machineDetails.getContentPane().add(lblStatus);
        lblStatus.setBounds(420, 60, 80, 16);

        lblDateOfDelivery.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDateOfDelivery.setForeground(new java.awt.Color(0, 102, 0));
        lblDateOfDelivery.setText("*Date of delivery");
        machineDetails.getContentPane().add(lblDateOfDelivery);
        lblDateOfDelivery.setBounds(420, 120, 130, 16);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Date of delivery");
        machineDetails.getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 120, 110, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Status");
        machineDetails.getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 60, 43, 16);

        btnSendMail.setBackground(new java.awt.Color(0, 153, 153));
        btnSendMail.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSendMail.setForeground(new java.awt.Color(255, 255, 255));
        btnSendMail.setText("Send email");
        btnSendMail.setMaximumSize(new java.awt.Dimension(200, 200));
        btnSendMail.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });
        machineDetails.getContentPane().add(btnSendMail);
        btnSendMail.setBounds(390, 170, 140, 30);

        btnGenerateBill.setBackground(new java.awt.Color(0, 153, 153));
        btnGenerateBill.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGenerateBill.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateBill.setText("Genarate bill");
        btnGenerateBill.setMaximumSize(new java.awt.Dimension(200, 200));
        btnGenerateBill.setMinimumSize(new java.awt.Dimension(200, 200));
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });
        machineDetails.getContentPane().add(btnGenerateBill);
        btnGenerateBill.setBounds(230, 170, 150, 30);

        add(machineDetails);
        machineDetails.setBounds(270, 230, 566, 240);

        tblReqfromClients.setBackground(new java.awt.Color(204, 255, 204));
        tblReqfromClients.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblReqfromClients.setForeground(new java.awt.Color(102, 0, 102));
        tblReqfromClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RequestId", "Machine", "Code", "Quantity", "Price", "Role", "Sender", "Status", "Receiver", "Date of Delivery"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReqfromClients);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 1250, 170);

        btnSendSupplier.setBackground(new java.awt.Color(0, 153, 153));
        btnSendSupplier.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSendSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSendSupplier.setText("Send to Suppliers ");
        btnSendSupplier.setMaximumSize(new java.awt.Dimension(200, 200));
        btnSendSupplier.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSendSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSupplierActionPerformed(evt);
            }
        });
        add(btnSendSupplier);
        btnSendSupplier.setBounds(30, 300, 200, 70);

        btnViewDet.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewDet.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDet.setText("View Detail");
        btnViewDet.setMaximumSize(new java.awt.Dimension(200, 200));
        btnViewDet.setMinimumSize(new java.awt.Dimension(200, 200));
        btnViewDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetActionPerformed(evt);
            }
        });
        add(btnViewDet);
        btnViewDet.setBounds(30, 240, 200, 40);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 533, 55, 39);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSupplierActionPerformed
        
// TODO add your handling code here:
        int selectedRow = tblReqfromClients.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            MachineRequest req = (MachineRequest) tblReqfromClients.getValueAt(selectedRow, 0);

            if (req.getStatus().equalsIgnoreCase("Requested")) {
                for (Network net : network) {
                    for (Enterprise e : net.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                            if (o instanceof SupplierOrganization) {
                                o.getWorkQueue().getWorkRequestList().add(req);
                                req.setStatus("Pending");
                                populateTable();

                            }
                        }
                    }
                }
                //JOptionPane.showMessageDialog(null, "Sent to Supplier");
            } else if (req.getStatus().equalsIgnoreCase("Pending")) {
                JOptionPane.showMessageDialog(null, "Supplier Notified. Waiting for Reply!!");
            } else if (req.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Order Completed!!");
            }
        }

    }//GEN-LAST:event_btnSendSupplierActionPerformed

    public void populateLabels() {
        int selectedrow = tblReqfromClients.getSelectedRow();
        if (selectedrow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            machineDetails.show();
            MachineRequest machine = (MachineRequest) tblReqfromClients.getValueAt(selectedrow, 0);
            lblMachineName.setText(machine.getMachine().getName());
            lblCode.setText(machine.getMachine().getCode());

            lblQty.setText(String.valueOf(machine.getRequestQuantity()));
            lblPrise.setText(String.valueOf(machine.getTotalPrice()));
            lblQty.setText(String.valueOf(machine.getRequestQuantity()));

            double totalPrice = machine.getMachine().getPrice() * machine.getMachine().getQuantity();
            DecimalFormat df = new DecimalFormat("#.00");

            double totalAmount = machine.getTotalPrice();
            lblPrise.setText(df.format(totalAmount));
            lblSender.setText(machine.getSender().getUsername());
            lblStatus.setText(machine.getStatus());

            if (machine.getStatus().equalsIgnoreCase("Requested")) {
                lblReceiver.setText("");
                lblDateOfDelivery.setText("");

            } else if (machine.getStatus().equalsIgnoreCase("Pending")) {
                lblReceiver.setText("Notified");
                lblDateOfDelivery.setText("-");

            } else if (machine.getStatus().equalsIgnoreCase("Completed")) {
                lblReceiver.setText(machine.getReceiver().getEmployee().getName());
                lblDateOfDelivery.setText(machine.getDayOfDelivery());
                btnGenerateBill.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please select Machine from Table ");
            }
        }

    }
    
    private void btnViewDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetActionPerformed
        // TODO add your handling code here:
       populateLabels();
       btnSendMail.setEnabled(false);
    }//GEN-LAST:event_btnViewDetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
        populateLabels();
        btnSendMail.setEnabled(true);
        try {
            // TODO add your handling code here:
            Document doc = new Document();
            try {
                int i = 0;
                PdfWriter.getInstance(doc, new FileOutputStream("Bill_" + lblSender.getText() + ".pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(RequestsForMachinefromClientJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.open();
            Date d = new Date();
            DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
            String szDate = oDateFormat.format(d);

            doc.add(new Paragraph(("__________________________ MedicLoan _____________________________" + szDate)));
            doc.add(new Paragraph(lblSender.getText()));

            doc.add(new Paragraph(lblMachineName.getText() +"-                                                         "+lblCode.getText()));
            doc.add(new Paragraph("Quantity "+"                                                               "+lblQty.getText()));
            doc.add(new Paragraph("Total Price "+"                                                          "+lblPrise.getText()));
            doc.add(new Paragraph("Date of delivery "+"                                                   "+lblDateOfDelivery.getText()));
            System.out.println("Document created");
            doc.close();

        } catch (DocumentException ex) {
            Logger.getLogger(RequestsForMachinefromClientJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "Bill_" + lblSender.getText() + ".pdf");

        } catch (Exception e) {
            System.out.println(e);
        }
        txtAttached.setText("Bill_" + lblSender.getText() + ".pdf");


    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        // TODO add your handling code here:
        emailBox.show();
        btnSendMail.setEnabled(false);
        tblReqfromClients.setEnabled(false);
        machineDetails.setEnabled(false);
        btnViewDet.setEnabled(false);
        btnSendSupplier.setEnabled(false);


    }//GEN-LAST:event_btnSendMailActionPerformed

    private void btnAttachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachedActionPerformed
        // TODO add your handling code here:

        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            txtAttached.setText(path);
            
        }
    }//GEN-LAST:event_btnAttachedActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        Email mail = new Email();
        //panchal.k@husky.neu.edu
        mail.sendEmail(txtMailAdd.getText(), txtMailSubject.getText(), txtMailMessage.getText(), "kranti1995@gmail.com", "kranti1995", "Jaygurudev151", txtAttached.getText());
        emailBox.hide();

        btnSendMail.setEnabled(true);
        tblReqfromClients.setEnabled(true);
        machineDetails.setEnabled(true);
        btnViewDet.setEnabled(true);
        btnSendSupplier.setEnabled(true);
        btnSendMail.setEnabled(false);
        
        
    }//GEN-LAST:event_btnSendActionPerformed

    private void emailBoxInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_emailBoxInternalFrameClosing
// TODO add your handling code here:
        
        btnSendMail.setEnabled(true);
        tblReqfromClients.setEnabled(true);
        machineDetails.setEnabled(true);
        btnViewDet.setEnabled(true);
        btnSendSupplier.setEnabled(true);
        btnSendMail.setEnabled(true);


    }//GEN-LAST:event_emailBoxInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttached;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendMail;
    private javax.swing.JButton btnSendSupplier;
    private javax.swing.JButton btnViewDet;
    private javax.swing.JInternalFrame emailBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblDateOfDelivery;
    private javax.swing.JLabel lblMachineName;
    private javax.swing.JLabel lblPrise;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblReceiver;
    private javax.swing.JLabel lblSender;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JInternalFrame machineDetails;
    private javax.swing.JTable tblReqfromClients;
    private javax.swing.JTextField txtAttached;
    private javax.swing.JTextField txtMailAdd;
    private javax.swing.JTextArea txtMailMessage;
    private javax.swing.JTextField txtMailSubject;
    // End of variables declaration//GEN-END:variables
}
