/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonLoginPage;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MachineRequest;
import Business.WorkQueue.TechnicianRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komal
 */
public class CallTechnicianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CallTechnicianJPanel
     */
    private JPanel container;
    private UserAccount ua;
    private MachineRequest machineReq;
    private Organization org;
    private Enterprise enterprise;
    private EcoSystem system;
    private TechnicianRequest techReq;

    public CallTechnicianJPanel(JPanel container, MachineRequest req, UserAccount ua, Organization org, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.machineReq = req;
        this.org = org;
        this.enterprise = enterprise;
        this.system = system;

        populateMachineRequest();
        buttonGroup1.clearSelection();
    }

    public void populateMachineRequest() {
        DefaultTableModel dtm = (DefaultTableModel) tblNotifyTechnician.getModel();
        dtm.setRowCount(0);

        Object row[] = new Object[7];
        row[0] = machineReq.getMachine().getName();
        row[1] = machineReq.getMachine().getCode();
        dtm.addRow(row);
    }

    public void populateTechnicianRequest() {
        DefaultTableModel dtm = (DefaultTableModel) tblNotifyTechnician.getModel();
        dtm.setRowCount(0);

        Object row[] = new Object[7];
        row[0] = techReq.getMachine().getName();
        row[1] = techReq.getMachine().getCode();
        row[2] = ((TechnicianRequest) techReq).getServiceType();
        row[3] = techReq.getStatus();
        row[4] = techReq.getReceiver();
        row[5] = ((TechnicianRequest) techReq).getServiceDateInString();

        dtm.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotifyTechnician = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProblemDesc = new javax.swing.JTextField();
        jRBMaintenance = new javax.swing.JRadioButton();
        jRBguidelines = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnViewReq = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        tblNotifyTechnician.setBackground(new java.awt.Color(204, 255, 204));
        tblNotifyTechnician.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNotifyTechnician.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblNotifyTechnician.setForeground(new java.awt.Color(102, 0, 102));
        tblNotifyTechnician.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Machine", "Code", "Type of service", "Notify", "Technician", "Possible date of Assistance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNotifyTechnician);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 45, 779, 43);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Notify Technician");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 109, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Problem Description:");
        add(jLabel7);
        jLabel7.setBounds(170, 260, 134, 16);

        txtProblemDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProblemDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemDescActionPerformed(evt);
            }
        });
        txtProblemDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProblemDescKeyPressed(evt);
            }
        });
        add(txtProblemDesc);
        txtProblemDesc.setBounds(310, 250, 286, 27);

        jRBMaintenance.setBackground(new java.awt.Color(255, 255, 255));
        jRBMaintenance.setForeground(new java.awt.Color(0, 102, 0));
        jRBMaintenance.setText("Maintenance");
        jRBMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMaintenanceActionPerformed(evt);
            }
        });
        add(jRBMaintenance);
        jRBMaintenance.setBounds(300, 190, 130, 23);

        jRBguidelines.setBackground(new java.awt.Color(255, 255, 255));
        jRBguidelines.setForeground(new java.awt.Color(0, 102, 0));
        jRBguidelines.setText("Guidelines");
        jRBguidelines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBguidelinesActionPerformed(evt);
            }
        });
        add(jRBguidelines);
        jRBguidelines.setBounds(460, 190, 120, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Type of Service:");
        add(jLabel8);
        jLabel8.setBounds(190, 190, 105, 16);

        btnSend.setBackground(new java.awt.Color(0, 153, 153));
        btnSend.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.setMaximumSize(new java.awt.Dimension(200, 200));
        btnSend.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend);
        btnSend.setBounds(310, 320, 180, 37);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 440, 55, 39);

        btnViewReq.setBackground(new java.awt.Color(0, 153, 153));
        btnViewReq.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewReq.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReq.setText("View all Requests >");
        btnViewReq.setMaximumSize(new java.awt.Dimension(200, 200));
        btnViewReq.setMinimumSize(new java.awt.Dimension(200, 200));
        btnViewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReqActionPerformed(evt);
            }
        });
        add(btnViewReq);
        btnViewReq.setBounds(600, 140, 180, 35);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProblemDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProblemDescActionPerformed

    private void txtProblemDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProblemDescKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtProblemDescKeyPressed

    private void jRBMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMaintenanceActionPerformed
        // TODO add your handling code here:
        if (jRBMaintenance.isSelected()) {
            jRBguidelines.isEnabled();
        }

    }//GEN-LAST:event_jRBMaintenanceActionPerformed

    private void jRBguidelinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBguidelinesActionPerformed
        // TODO add your handling code here:
        if (jRBguidelines.isSelected()) {
            jRBMaintenance.isEnabled();
        }
    }//GEN-LAST:event_jRBguidelinesActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNotifyTechnician.getSelectedRow();
        if (selectedRow >= 0) {
            String des = txtProblemDesc.getText();
            String type = "";
            if (jRBMaintenance.isSelected()) {
                type = "Maintenance";
            }
            if (jRBguidelines.isSelected()) {
                type = "Guidelines";
            }
            if (type.equals("")) {
                JOptionPane.showMessageDialog(null, "Please input type of service");
                return;
            } else if (des.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter Description");
                return;
            } else {
                techReq = new TechnicianRequest();
                techReq.setMachine(machineReq.getMachine());
                techReq.setSender(ua);
                org.getWorkQueue().getWorkRequestList().add(techReq);
                ua.getWorkQueue().getWorkRequestList().add(techReq);
                system.getWorkQueue().getWorkRequestList().add(techReq);
                techReq.setDescription(des);
                techReq.setServiceType(type);
                techReq.setStatus("Requested");
                techReq.setSender(ua);
                populateTechnicianRequest();
                JOptionPane.showMessageDialog(null, "Request send successfully");
                buttonGroup1.clearSelection();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select the request!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReqActionPerformed
        // TODO add your handling code here:
        ViewAllTechnicianRequestsJPanel vatrJPanel = new ViewAllTechnicianRequestsJPanel(container, ua, system);
        container.add("technician all request JPanel", vatrJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnViewReq;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRBMaintenance;
    private javax.swing.JRadioButton jRBguidelines;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JTable tblNotifyTechnician;
    private javax.swing.JTextField txtProblemDesc;
    // End of variables declaration//GEN-END:variables
}
