/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonLoginPage;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Machine.Machine;
import Business.Organization.Organization;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komal
 */
public class SuggestionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuggestionJPanel
     */
    private JPanel container;
    private UserAccount ua;
    private Organization org;
    private Enterprise enterprise;
    private EcoSystem system;
    
    public SuggestionJPanel(JPanel container,UserAccount ua, Organization org,Enterprise enterprise,EcoSystem system ) {
        initComponents();
        this.container =container;
        this.ua=ua;
        this.org=org;
        this.enterprise=enterprise;
        this.system=system;
        
        populateTable();
        
    }
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblRecommend.getModel();
        model.setRowCount(0);

        for (Supplier s : system.getSupplierCatalog().getSupplierList()) {
            for (Machine m : s.getMachineList().getMachineCatalog()) {
                if (m.getType().equalsIgnoreCase(ua.getHighestMachineType())){
                    if (m.isRecommend()) {
                        Object[] row = new Object[4];
                        row[0] = m;
                        row[1] = m.getCode();
                        row[2] = m.getType();
                        row[3] = m.getPrice();
                        model.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecommend = new javax.swing.JTable();
        btnBuyMachine = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Suggestions");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 79, 16);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 476, 55, 39);

        tblRecommend.setBackground(new java.awt.Color(204, 255, 204));
        tblRecommend.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblRecommend.setForeground(new java.awt.Color(102, 0, 102));
        tblRecommend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Machine", "Machine Code", "Machine Type", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblRecommend);

        add(jScrollPane2);
        jScrollPane2.setBounds(50, 50, 870, 320);

        btnBuyMachine.setBackground(new java.awt.Color(0, 153, 153));
        btnBuyMachine.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBuyMachine.setForeground(new java.awt.Color(255, 255, 255));
        btnBuyMachine.setText("<< Buy Machines ");
        btnBuyMachine.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBuyMachine.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBuyMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyMachineActionPerformed(evt);
            }
        });
        add(btnBuyMachine);
        btnBuyMachine.setBounds(50, 380, 177, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBuyMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyMachineActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Go back and Select Buy Machines Option !!!");

    }//GEN-LAST:event_btnBuyMachineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuyMachine;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JTable tblRecommend;
    // End of variables declaration//GEN-END:variables
}
