/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NGOAdmin;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Komal
 */
public class NGOAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    public NGOAdminWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise=enterprise;
        
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        btnMngOrg = new javax.swing.JButton();
        btnMngEmployee = new javax.swing.JButton();
        btnMngUser = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Administrative(Enterprise) Work Area JPanel ");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 297, 16);

        btnMngOrg.setBackground(new java.awt.Color(0, 153, 153));
        btnMngOrg.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMngOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnMngOrg.setText("Manage Organization");
        btnMngOrg.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMngOrg.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMngOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOrgActionPerformed(evt);
            }
        });
        add(btnMngOrg);
        btnMngOrg.setBounds(350, 190, 223, 50);

        btnMngEmployee.setBackground(new java.awt.Color(0, 153, 153));
        btnMngEmployee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMngEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnMngEmployee.setText("Manage Employee");
        btnMngEmployee.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMngEmployee.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMngEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEmployeeActionPerformed(evt);
            }
        });
        add(btnMngEmployee);
        btnMngEmployee.setBounds(350, 260, 223, 50);

        btnMngUser.setBackground(new java.awt.Color(0, 153, 153));
        btnMngUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMngUser.setForeground(new java.awt.Color(255, 255, 255));
        btnMngUser.setText("Manage User");
        btnMngUser.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMngUser.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMngUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUserActionPerformed(evt);
            }
        });
        add(btnMngUser);
        btnMngUser.setBounds(350, 330, 223, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Enterprise");
        add(jLabel7);
        jLabel7.setBounds(360, 130, 67, 16);

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(0, 102, 0));
        valueLabel.setText("*Enterprise");
        add(valueLabel);
        valueLabel.setBounds(440, 130, 75, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOrgActionPerformed
        // TODO add your handling code here:
        NGOManageOrganizationJPanel orgJPanel = new NGOManageOrganizationJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
        userProcessContainer.add("organization JPanel", orgJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnMngOrgActionPerformed

    private void btnMngEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEmployeeActionPerformed
        // TODO add your handling code here:
        NGOManageEmployeeJPanel manageEmployeeJPanel = new NGOManageEmployeeJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
        userProcessContainer.add("Manage Enterprise JPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngEmployeeActionPerformed

    private void btnMngUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUserActionPerformed
        // TODO add your handling code here:
        NGOManageUserAccountJPanel manageUserAccountJPanel = new NGOManageUserAccountJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("Enterprise Admin JPanel", manageUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngEmployee;
    private javax.swing.JButton btnMngOrg;
    private javax.swing.JButton btnMngUser;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
