/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Komal
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount ua;
    private EcoSystem system;
    private SupplierOrganization org;
    private Supplier s;
    
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount ua, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua=ua;
        this.system=system;
        this.org=(SupplierOrganization)organization;
        lblSupplierName.setText(ua.getEmployee().getName());
        
        for (Supplier supplier : this.system.getSupplierCatalog().getSupplierList()) {
            if (this.ua.getEmployee().getName().equalsIgnoreCase(supplier.getSupplierName())) {
                this.s = supplier;
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomername1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMachineRequest = new javax.swing.JButton();
        lblSupplierName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAssigntoMe1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Supplier Work Area");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 126, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        btnMachineRequest.setBackground(new java.awt.Color(0, 153, 153));
        btnMachineRequest.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMachineRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnMachineRequest.setText("View Machine Request");
        btnMachineRequest.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMachineRequest.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMachineRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachineRequestActionPerformed(evt);
            }
        });
        add(btnMachineRequest);
        btnMachineRequest.setBounds(440, 310, 213, 60);

        lblSupplierName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSupplierName.setForeground(new java.awt.Color(0, 102, 0));
        lblSupplierName.setText("*Supplier name");
        add(lblSupplierName);
        lblSupplierName.setBounds(56, 38, 99, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Name:");
        add(jLabel7);
        jLabel7.setBounds(10, 38, 40, 16);

        btnAssigntoMe1.setBackground(new java.awt.Color(0, 153, 153));
        btnAssigntoMe1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssigntoMe1.setForeground(new java.awt.Color(255, 255, 255));
        btnAssigntoMe1.setText("Add Machine");
        btnAssigntoMe1.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe1.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigntoMe1ActionPerformed(evt);
            }
        });
        add(btnAssigntoMe1);
        btnAssigntoMe1.setBounds(440, 210, 213, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMachineRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMachineRequestActionPerformed
        // TODO add your handling code here:
         ViewMachineRequestJPanel viewMachineJp = new ViewMachineRequestJPanel(userProcessContainer,ua,s,system);
        userProcessContainer.add("view machine JPanel", viewMachineJp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);   
        
       
    }//GEN-LAST:event_btnMachineRequestActionPerformed

    private void btnAssigntoMe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigntoMe1ActionPerformed
        // TODO add your handling code here:
        AddNewMachineJPanel addMachineJp = new AddNewMachineJPanel(userProcessContainer,ua,s,system);
        userProcessContainer.add("add new machine JPanel", addMachineJp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
        
        
    }//GEN-LAST:event_btnAssigntoMe1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntoMe1;
    private javax.swing.JButton btnMachineRequest;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblSupplierName;
    // End of variables declaration//GEN-END:variables
}
