/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Machine.Machine;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MachineRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komal
 */
public class ViewMachineRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMachineRequestJPanel
     */
    private JPanel container;
    private EcoSystem system;
    private UserAccount ua;
    private Supplier s;

    public ViewMachineRequestJPanel(JPanel container, UserAccount ua,Supplier s, EcoSystem system) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.system = system;
        this.s=s;
        populateTable();
        estimatedDate.setDate(new Date());

    }

    public void populateTable() {

        boolean flag;

        DefaultTableModel model = (DefaultTableModel) tblMachineRequests.getModel();

        model.setRowCount(0);
        flag = false;
        for (WorkRequest work : system.getWorkQueue().getWorkRequestList()) {
            if (work instanceof MachineRequest) {
                if (work.getStatus().equals("Pending") || work.getStatus().equals("Completed")) {
                    Object[] row = new Object[8];
                    row[0] = work;
                    row[1] = work.getMachine();
                    row[2] = work.getMachine().getCode();
                    row[3] = ((MachineRequest) work).getRequestQuantity();
                    row[4] = work.getSender();
                    row[5] = work.getReceiver();
                    row[6] = work.getStatus();
                    row[7] = work.getDayOfDelivery();
                    model.addRow(row);
                    flag = true;
                }
            }
            if (flag == false) {
                JOptionPane.showMessageDialog(null, "Please Add Machines");

            }

        }
    }


      /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        lblCustomername3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMachineRequests = new javax.swing.JTable();
        btnAssigntoMe = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        estimatedDate = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(10, 11, 56, 16);

        lblCustomername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername1.setText("Requests for Machine");
        add(lblCustomername1);
        lblCustomername1.setBounds(72, 11, 141, 16);

        lblCustomername3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomername3.setForeground(new java.awt.Color(0, 102, 0));
        lblCustomername3.setText("Estimated Date of Delivery");
        add(lblCustomername3);
        lblCustomername3.setBounds(80, 350, 173, 16);

        tblMachineRequests.setBackground(new java.awt.Color(204, 255, 204));
        tblMachineRequests.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblMachineRequests.setForeground(new java.awt.Color(102, 0, 102));
        tblMachineRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Machine", "Code", "Quantity", "Sender", "Receiver", "Status", "Date Of Delivery"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMachineRequests);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 900, 230);

        btnAssigntoMe.setBackground(new java.awt.Color(0, 153, 153));
        btnAssigntoMe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssigntoMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssigntoMe.setText("Assign to Me");
        btnAssigntoMe.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigntoMeActionPerformed(evt);
            }
        });
        add(btnAssigntoMe);
        btnAssigntoMe.setBounds(470, 330, 170, 50);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 450, 55, 39);

        estimatedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedDateActionPerformed(evt);
            }
        });
        add(estimatedDate);
        estimatedDate.setBounds(270, 350, 140, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssigntoMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigntoMeActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        int selectedRow = tblMachineRequests.getSelectedRow();

        if (selectedRow >= 0) {
            MachineRequest req = (MachineRequest) tblMachineRequests.getValueAt(selectedRow, 0);

            if (req.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed");
                return;
            }
            for (Machine m : s.getMachineList().getMachineCatalog()) {
                if (req.getMachine().equals(m)) {
                    flag = true;
                    Date oDate = estimatedDate.getDate();
                    Date now = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
                    if ((sdf.format(oDate).equals(sdf.format(now))) || (sdf.format(oDate).compareTo(sdf.format(now))) > 0) {
                        DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
                        String szDate = oDateFormat.format(oDate);
                        req.setReceiver(this.ua);
                        req.setStatus("Completed");

                        req.setDayOfDelivery(szDate);

                        estimatedDate.setDate(oDate);
                        populateTable();
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Date of Delivery");
                        return;
                    }
                }
            }
            if (flag == false) {
                JOptionPane.showMessageDialog(null, "You cannot request as you dont have the machine!!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Request to process");
            return;
        }

    }//GEN-LAST:event_btnAssigntoMeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void estimatedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimatedDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntoMe;
    private javax.swing.JButton btnBack;
    private org.jdesktop.swingx.JXDatePicker estimatedDate;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblCustomername3;
    private javax.swing.JTable tblMachineRequests;
    // End of variables declaration//GEN-END:variables
}
